### ISSUE TITLE
cdn link from the documentation is KO

### ISSUE THREAD

**Issue by k-bruneau** [recogizer/gauge-chart#8]
Hello guys, the link to cdn is no longer valid from the README. Maybe broken since yesterday build ?
Can you look into it ?

**Comment by mmaltsev** [comment]
Hi @k-bruneau!

Indeed, yesterday build is the reason. I'm on it, will be fixed soon.

**Comment by mmaltsev** [comment]
Fixed. Version `0.5.1`.
